### ISSUE TITLE
在生产上能稳定运行吗

### ISSUE THREAD

**Issue by huahuayu** [qshuai/go-electrum#1]
你好，请问这个版本在生产上能稳定运行吗？

在readme中这段示例代码直接painc了, 而且看到有依赖于这个地址 electrum.dragonzone.net:50001，如果这里不提供服务了怎么办？
``` go
package main

import (
  "log"

  "github.com/qshuai/go-electrum/electrum"
)

func main() {
	node := electrum.NewNode()
	if err := node.ConnectTCP("electrum.dragonzone.net:50001"); err != nil {
		log.Fatal(err)
	}
	balance, err := node.BlockchainAddressGetBalance("1NS17iag9jJgTHD1VXjvLCEnZuQ3rJDE9L")
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Address balance: %+v", balance)
}
``` 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x11284ee]

goroutine 1 [running]:
github.com/qshuai/go-electrum/electrum.(*Node).BlockchainAddressGetBalance(0xc420102000, 0x118821c, 0x22, 0x0, 0x0, 0xc4200107b0)
	~/5-goland/src/github.com/qshuai/go-electrum/electrum/blockchain.go:87 +0x11e
main.main()
	~/5-goland/src/thewaytogo/electrumClient.go:14 +0x181

Process finished with exit code 2
```

**Comment by qshuai** [comment]
Thanks for this issue!

I do not know `electrum.dragonzone.net:50001` server details(which blockchain, mainnet/testnet and 
 so on). So I recommend to use my server `39.104.125.149:9629` for bitcoin-cash testnet.

Now, please refer to the updated `README.md`.

**Comment by huahuayu** [comment]
Thank you for reply, let me try... actually before raising this issue, I have sent you a mail yesterday :) maybe you missed it.

so, what's server behind the IP 39.104.125.149:9629, can I control it by myself?

**Comment by qshuai** [comment]
The server relative to `39.104.125.149:9629` is a private service server. So you can set up a [Electrumx](https://github.com/kyuupichan/electrumx) server by yourself.
