### ISSUE TITLE
Usage of atomic is not atomic

### ISSUE THREAD

**Issue by alokmenghrajani** [qshuai/go-electrum#2]
```
	msg := request{
		Id:     atomic.LoadUint64(&n.nextId),
		Method: method,
		Params: params,
	}
	atomic.AddUint64(&n.nextId, 1)
```
is not the proper way to use the atomic package. You cannot guarantee that another goroutine will not read `n.nextId` between the time the code reads and then updates the value.

The correct pattern looks like:
```
msg := request{
  Id: atomic.AddUint64(&nextId, 1)
  ...
}
````

**Comment by qshuai** [comment]
Thanks very much!
